name: Lint & Tests

on:  
  push:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Run linters and Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Restore node_modules cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ github.event.inputs.cacheBustKey }}

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: yarn --frozen-lockfile

      - name: Tests
        run: yarn test
